name: Deploy
on: 
  push:
    branches:
      - master
jobs:
  Build and Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
    - name: Install, build, smoke, deploy
      run: |
        npm run deploy
      env:
        CI: true
    
    - run: echo "🍏 This job's status is ${{ job.status }}."