name: Deploy
on: 
  push:
    branches:
      - master
jobs:
  Build and Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install, build, smoke, deploy
        run: |
          npm ci
          npm run deploy
        env:
          CI: true